version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/www"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
